name: repeatmasker_repeatmasker
description: |
  Screening DNA sequences for interspersed repeats and low complexity DNA sequences

keywords:
  - genome
  - annotation
  - repeat
  - mask

tools:
  - repeatmasker:
      description: |
        RepeatMasker is a program that screens DNA sequences for interspersed
        repeats and low complexity DNA sequences
      homepage: "https://www.repeatmasker.org/"
      documentation: "https://www.repeatmasker.org/webrepeatmaskerhelp.html"
      tool_dev_url: "https://github.com/rmhubley/RepeatMasker"
      licence: ["Open Software License v. 2.1"]
      identifier: biotools:repeatmasker

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: Genome assembly
        pattern: "*.{fasta,fa,fas,fsa,faa,fna}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - lib:
      type: file
      description: Custom library (e.g. from another species)
      pattern: "*.{fasta,fa,fas,fsa,faa,fna}"
      ontologies:
        - edam: http://edamontology.org/format_1929 # FASTA
output:
  masked:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - ${prefix}.masked:
          type: file
          description: Masked fasta
          pattern: "*.{masked}"
          ontologies: []
  out:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - ${prefix}.out:
          type: file
          description: RepeatMasker annotation output file
          pattern: "*.{out}"
          ontologies: []
  tbl:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - ${prefix}.tbl:
          type: file
          description: Summary statistics table
          pattern: "*.{tbl}"
          ontologies: []
  gff:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - ${prefix}.gff:
          type: file
          description: GFF annotation file
          pattern: "*.{gff}"
          ontologies:
            - edam: http://edamontology.org/format_2305
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@kherronism"
  - "@gallvp"

maintainers:
  - "@kherronism"
  - "@gallvp"
